# Generated by Django 3.1.5 on 2021-01-18 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='users',
            new_name='guests',
        ),
    ]
